spring:
  application:
    name: config-client

  cloud:
    bus:
      enabled: true

  config:
    import: "configserver:"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, busrefresh
#        exclude: env, beans # 특정 엔드포인트를 제외하려는 경우
    
    
    